# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      id: cache-node
      uses: actions/cache@v3
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          node-

    - name: check cache
      if: steps.cache-node.outputs.cache-hit != 'true'
      run: yarn install

    - name: lint, build, bench, test
      run: |
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        echo '            lint -> build -> bench -> test'
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        yarn all
        yarn bench && yarn test
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        echo '                   batch-rmc-test'
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        yarn grmc-test:cjs
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        echo '                    run benchmark'
        echo "- - - - - - - - - - - - - - - - - - - - - - - - - - - -"
        yarn benchmark
